SELECT
    f1.CATEGORY AS CATETORY,
    f1.PRICE AS MAX_PRICE,
    f1.PRODUCT_NAME AS PRODUCT_NAME
FROM FOOD_PRODUCT AS f1
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MP
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS f2
    ON f1.CATEGORY = f2.CATEGORY AND f1.PRICE = f2.MP
ORDER BY f1.PRICE DESC;
