WITH RECURSIVE R AS (
    SELECT ID, PARENT_ID, 0 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID AS ID, E.PARENT_ID AS PARENT_ID, R.GENERATION + 1 AS GENERATION
    FROM R
    LEFT JOIN ECOLI_DATA AS E
    ON R.ID = E.PARENT_ID
    WHERE R.ID IS NOT NULL
)
SELECT COUNT(GENERATION) AS COUNT, GENERATION
FROM R
WHERE ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION ASC;
