WITH m AS (
    SELECT `VIEWS`
    FROM USED_GOODS_BOARD
    ORDER BY `VIEWS` DESC
    LIMIT 1
)
SELECT CONCAT('/home/grep/src/', b.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS b
JOIN USED_GOODS_FILE AS f
ON b.BOARD_ID = f.BOARD_ID
JOIN m
ON b.`VIEWS` = m.`VIEWS`
ORDER BY FILE_ID DESC;
