SELECT
    a.MCDP_CD AS `진료과 코드`,
    COUNT(a.MCDP_CD) AS `5월예약건수`
FROM (
    SELECT MCDP_CD
    FROM APPOINTMENT
    WHERE YEAR(APNT_YMD) = 2022 AND MONTH(APNT_YMD) = 5
) AS a
GROUP BY a.MCDP_CD
ORDER BY `5월예약건수` ASC, a.MCDP_CD ASC;
