SELECT *
FROM (
    SELECT ID, "LOW" AS SIZE
    FROM ECOLI_DATA
    WHERE SIZE_OF_COLONY <= 100
    UNION
    SELECT ID, "MEDIUM" AS SIZE
    FROM ECOLI_DATA
    WHERE 100 <= SIZE_OF_COLONY AND SIZE_OF_COLONY < 1000
    UNION
    SELECT ID, "HIGH" AS SIZE
    FROM ECOLI_DATA
    WHERE 1000 <= SIZE_OF_COLONY
) AS A
ORDER BY ID;

SELECT
    ID,
    CASE
        WHEN SIZE_OF_COLONY <= 100 THEN "LOW"
        WHEN SIZE_OF_COLONY <= 1000 THEN "MEDIUM"
        ELSE "HIGH"
    END AS SIZE
FROM ECOLI_DATA
ORDER BY ID ASC;
