SELECT DISTINCT(c.CAR_ID) AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
ON
    CAR_TYPE = '세단'
    AND c.CAR_ID = h.CAR_ID
    AND MONTH(h.START_DATE) = 10
ORDER BY CAR_ID DESC;
