SELECT TARGET.ITEM_ID, TARGET.ITEM_NAME, TARGET.RARITY
FROM ITEM_INFO AS TARGET
JOIN ITEM_TREE
ON TARGET.ITEM_ID = ITEM_TREE.ITEM_ID
JOIN ITEM_INFO AS PARENT
ON ITEM_TREE.PARENT_ITEM_ID = PARENT.ITEM_ID
WHERE PARENT.RARITY = "RARE"
ORDER BY TARGET.ITEM_ID DESC;
