SELECT BOOK_ID, AUTHOR_NAME, PUBLISHED_DATE
FROM (
    SELECT BOOK_ID, AUTHOR_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
    FROM BOOK
    WHERE CATEGORY = '경제'
) AS b
JOIN AUTHOR
ON b.AUTHOR_ID = AUTHOR.AUTHOR_ID
ORDER BY PUBLISHED_DATE ASC;
