WITH RECURSIVE t (H) AS (
    SELECT 0
    UNION ALL
    SELECT H + 1
    FROM t
    WHERE H < 23
)
SELECT t.H AS HOUR, COUNT(ANIMAL_ID) AS `COUNT`
FROM t
LEFT JOIN ANIMAL_OUTS
ON t.H = HOUR(DATETIME)
GROUP BY t.H
ORDER BY HOUR ASC;
