SELECT
    eg.SCORE AS SCORE,
    HR_EMPLOYEES.EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM HR_EMPLOYEES
JOIN HR_DEPARTMENT
ON HR_EMPLOYEES.DEPT_ID = HR_DEPARTMENT.DEPT_ID
JOIN (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) AS eg
ON HR_EMPLOYEES.EMP_NO = eg.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;

WITH eg AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT
    eg.SCORE AS SCORE,
    HR_EMPLOYEES.EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM HR_EMPLOYEES
JOIN HR_DEPARTMENT
ON HR_EMPLOYEES.DEPT_ID = HR_DEPARTMENT.DEPT_ID
JOIN eg
ON HR_EMPLOYEES.EMP_NO = eg.EMP_NO
WHERE SCORE = (SELECT MAX(SCORE) FROM eg);

SELECT
    SUM(SCORE) AS SCORE,
    HR_EMPLOYEES.EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM HR_EMPLOYEES
JOIN HR_GRADE
ON HR_EMPLOYEES.EMP_NO = HR_GRADE.EMP_NO
GROUP BY HR_EMPLOYEES.EMP_NO
HAVING SCORE = (
    SELECT SUM(SCORE)
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1
);
