SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS,
    ROUND(AVG(REVIEW.REVIEW_SCORE), 2) AS AVG_SCORE
FROM REST_INFO AS INFO, REST_REVIEW AS REVIEW
WHERE INFO.ADDRESS LIKE "서울%" AND INFO.REST_ID = REVIEW.REST_ID
GROUP BY REVIEW.REST_ID
ORDER BY AVG_SCORE DESC, INFO.FAVORITES DESC;

SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS,
    REVIEW.AVG_SCORE
FROM REST_INFO AS INFO
JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS AVG_SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) AS REVIEW
ON INFO.REST_ID = REVIEW.REST_ID
WHERE INFO.ADDRESS LIKE "서울%"
ORDER BY AVG_SCORE DESC, INFO.FAVORITES DESC;
