SELECT *
FROM (
    SELECT
        c.CAR_ID AS CAR_ID,
        c.CAR_TYPE AS CAR_TYPE,
        c.DAILY_FEE * 30 * dp.EFFECTIVE_RATE DIV 100 AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS c
    JOIN (
        SELECT CAR_TYPE, 100 - DISCOUNT_RATE AS EFFECTIVE_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE IN ('세단', 'SUV') AND DURATION_TYPE = '30일 이상'
    ) AS dp
    ON c.CAR_TYPE = dp.CAR_TYPE
    WHERE
        NOT EXISTS (
            SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS rh
            WHERE
                c.CAR_ID = rh.CAR_ID
                AND (YEAR(START_DATE) < 2022 OR YEAR(START_DATE) = 2022 AND MONTH(START_DATE) <= 11)
                AND (YEAR(END_DATE) > 2022 OR YEAR(END_DATE) = 2022 AND MONTH(END_DATE) >= 11)
        )
) AS t
WHERE 500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
