SELECT
    DISTINCT(c1.CAR_ID) AS CAR_ID,
    IF(c2.CAR_ID IS NULL, "대여 가능", "대여중") AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS c1
LEFT JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE "2022-10-16" BETWEEN START_DATE AND END_DATE
) AS c2
ON c1.CAR_ID = c2.CAR_ID
ORDER BY c1.CAR_ID DESC;
