SELECT THIRD_GEN.ID AS ID
FROM ECOLI_DATA AS FIRST_GEN
JOIN ECOLI_DATA AS SECOND_GEN
ON FIRST_GEN.ID = SECOND_GEN.PARENT_ID
JOIN ECOLI_DATA AS THIRD_GEN
ON SECOND_GEN.ID = THIRD_GEN.PARENT_ID
WHERE FIRST_GEN.PARENT_ID IS NULL
ORDER BY ID ASC;
