WITH T AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT
    T.YEAR AS YEAR,
    T.MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA
LEFT JOIN T
    ON YEAR(DIFFERENTIATION_DATE) = YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;
