SELECT E.ID AS ID, E.GENOTYPE AS GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS P
JOIN ECOLI_DATA AS E
ON P.ID = E.PARENT_ID
WHERE P.GENOTYPE ^ (E.GENOTYPE & P.GENOTYPE) = 0
ORDER BY E.ID;
