WITH u AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT
    o.YEAR AS YEAR,
    o.MONTH AS MONTH,
    COUNT(*) AS PURCHASED_USERS,
    ROUND(COUNT(*) / t.TOTAL, 1) AS PURCHASED_RATIO
FROM u
JOIN (
    SELECT
        YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH,
        u.USER_ID AS USER_ID
    FROM u
    JOIN ONLINE_SALE AS o
    ON u.USER_ID = o.USER_ID
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), u.USER_ID
) AS o
ON u.USER_ID = o.USER_ID
JOIN (
    SELECT COUNT(*) AS TOTAL
    FROM u
) AS t
ON true
GROUP BY o.YEAR, o.MONTH
ORDER BY YEAR ASC, MONTH ASC;
