WITH RECURSIVE r (PRICE_GROUP) AS (
    SELECT 0
    UNION ALL
    SELECT PRICE_GROUP + 10000
    FROM r
    WHERE PRICE_GROUP < (SELECT MAX(PRICE) FROM PRODUCT) - 10000
)
SELECT PRICE_GROUP, COUNT(PRODUCT_ID) AS PRODUCTS
FROM r
JOIN PRODUCT
ON PRICE_GROUP <= PRICE AND PRICE < PRICE_GROUP + 10000
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC;
