WITH fi AS (
    SELECT
        ID,
        FISH_TYPE,
        CASE
            WHEN LENGTH IS NULL OR LENGTH <= 10 THEN 10
            ELSE LENGTH
        END AS LENGTH
    FROM FISH_INFO
)
SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM fi
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE ASC;
