SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS f1
JOIN (
    SELECT FISH_INFO.FISH_TYPE AS FT, MAX(LENGTH) AS ML
    FROM FISH_INFO
    JOIN FISH_NAME_INFO
    ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
    GROUP BY FISH_INFO.FISH_TYPE
) AS f2
ON f1.FISH_TYPE = f2.FT AND f1.LENGTH = f2.ML
JOIN FISH_NAME_INFO
ON f1.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
ORDER BY ID ASC;
