SELECT REST_INFO.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MF
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS R
ON REST_INFO.FOOD_TYPE = R.FOOD_TYPE AND REST_INFO.FAVORITES = R.MF
ORDER BY REST_INFO.FOOD_TYPE DESC;
