SELECT APNT_NO, PT_NAME, p.PT_NO AS PT_NO, d.MCDP_CD AS MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT AS p
JOIN APPOINTMENT AS a
ON
    p.PT_NO = a.PT_NO
    AND YEAR(APNT_YMD) = 2022 AND MONTH(APNT_YMD) = 4 AND DAY(APNT_YMD) = 13
    AND APNT_CNCL_YN = 'N'
    AND MCDP_CD = 'CS'
JOIN DOCTOR AS d
ON a.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD ASC;
