SELECT
    HISTORY_ID,
    DAILY_FEE
        * (1 + DATEDIFF(END_DATE, START_DATE))
        * (100 - IFNULL(REGEXP_REPLACE(DISCOUNT_RATE, '\\%', ''), 0)) DIV 100 AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
ON c.CAR_ID = h.CAR_ID AND c.CAR_TYPE = '트럭'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS p
ON
    p.CAR_TYPE = '트럭'
    AND (
        DATEDIFF(END_DATE, START_DATE) BETWEEN 6 AND 28 AND DURATION_TYPE = '7일 이상'
        OR DATEDIFF(END_DATE, START_DATE) BETWEEN 29 AND 88 AND DURATION_TYPE = '30일 이상'
        OR DATEDIFF(END_DATE, START_DATE) >= 89 AND DURATION_TYPE = '90일 이상'
    )
ORDER BY FEE DESC, HISTORY_ID DESC;
